// Code generated by mockery v2.42.3. DO NOT EDIT.

// Copyright (c) Abstract Machines

package mocks

import (
	context "context"

	activitylog "github.com/absmach/magistrala/activitylog"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// ReadAll provides a mock function with given fields: ctx, token, page
func (_m *Service) ReadAll(ctx context.Context, token string, page activitylog.Page) (activitylog.ActivitiesPage, error) {
	ret := _m.Called(ctx, token, page)

	if len(ret) == 0 {
		panic("no return value specified for ReadAll")
	}

	var r0 activitylog.ActivitiesPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, activitylog.Page) (activitylog.ActivitiesPage, error)); ok {
		return rf(ctx, token, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, activitylog.Page) activitylog.ActivitiesPage); ok {
		r0 = rf(ctx, token, page)
	} else {
		r0 = ret.Get(0).(activitylog.ActivitiesPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, activitylog.Page) error); ok {
		r1 = rf(ctx, token, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, activity
func (_m *Service) Save(ctx context.Context, activity activitylog.Activity) error {
	ret := _m.Called(ctx, activity)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, activitylog.Activity) error); ok {
		r0 = rf(ctx, activity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
