# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

FROM alpine:3.22 AS alpine

FROM scratch
ARG SVC
COPY $SVC /exe
COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
ENTRYPOINT ["/exe"]
